#!/usr/bin/env bash

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
dry="0"

while [[ $# > 0 ]]; do
    if [[ "$1" == "--dry" ]]; then
        dry="1"
    fi
    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute: $@"
    if [[ $dry == "1" ]]; then
        return
    fi

    "$@"
}

log "--------- dev-env ---------"

if [[ -z "$XDG_CONFIG_HOME" ]]; then
    XDG_CONFIG_HOME="$HOME/.config"
fi

copy_dir() {
    from=$1
    to=$2
    pushd $from > /dev/null
    dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
    for dir in $dirs; do
        execute rm -rf $to/$dir
        execute cp -r $dir $to/$dir
    done
    popd > /dev/null
}


copy_tree() {
    from="$1"
    to="$2"
    name=$(basename "$from")
    dest="$to/$name"

    execute rm -rf "$dest"
    execute cp -r "$from" "$dest"
}

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)
   execute rm $to/$name 
    execute cp $from $to/$name
}

copy_tree .ssh $HOME
copy_tree .config $XDG_CONFIG_HOME
copy_tree ./personal $HOME
copy_tree .local $HOME/.local
#copy_file .specialconfig $HOME
copy_file .home/.xinitrc $HOME
copy_file .home/.zshrc $HOME
copy_file .home/.zsh_profile $HOME

